name: notif

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_TOKEN }}
          message: ${{ github.event.commits[0].message }}
          username: ${{ github.event.commits[0].author.name }}
          avatar: ${{ github.event.commits[0].author.avatar_url }}