name: notif

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: cl8dep/action-discord@0.1
        with:
          webhook: ${{ secrets.DISCORD_TOKEN }}
          message: ${{ github.event.commits[0].message }}
          username: ${{ github.event.commits[0].author.name }}
          avatar: ${{ github.event.commits[0].author.avatar_url }}