name: notif

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - name: test avatar url
        run: echo "https://github.com/${{ github.event.commits[0].author.login }}.png"
      - name: Notify Discord
        uses: cl8dep/action-discord@0.1
        with:
          webhook: ${{ secrets.DISCORD_TOKEN }}
          message: "${{ github.event.commits[0].message }}\nCommit: [${{ github.sha }}](<${{ github.event.commits[0].url }}>)"
          username: ${{ github.event.commits[0].author.name }}
          avatar: "https://github.com/${{ github.event.commits[0].author.login }}.png"