
name: test_lint

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Delta TypeScript Graph
        uses: ysk8hori/delta-typescript-graph-action@v1.0.5
      
      - name: Typecheck
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
        
            